apiVersion: v1
kind: Pod
metadata:
 name: pod-env-config
spec:
 containers:
 - name: sainginx
   image: nginx
   env: 
   - name: course
     valueFrom:
      configMapKeyRef:
        name: course-config
        key: course
   - name: duration
     valueFrom:
      configMapKeyRef:
       name: course-config
       key: duration