apiVersion: v1
kind: Pod
metadata: 
  name: sai-pod-resource
spec:
  containers:
   - image: nginx
     name: sai-nginx
     resources:
      requests:
       memory: "64Mi"
       cpu: "250m"
      limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
     - containerPort: 80
    
