---
apiVersion: v1
kind: Pod
metadata:
  name: sai-nginx
  labels:
   name: sai-service
spec:
  containers:
   - name: sainginx
     image: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: my-service
spec:
  selectors: 
  - name: sai-service
  ports:
   - protocal: TCP
    port: 80