---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    name: service-nginx
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    server: service-nginx
  ports:
    - protocol: TCP
      port: 80
      